--PROCEDIMIENTOS
drop PROCEDURE SP_INSERTAR_USUARIO;

CREATE OR REPLACE PROCEDURE SP_INSERTAR_USUARIO(
P_NOMBRE IN USUARIO.NOMBRE%TYPE,
P_APELLIDO IN USUARIO.APELLIDO%TYPE,
P_CONTRASENA IN USUARIO.CONTRASENA%TYPE,
P_CORREO IN USUARIO.CORREO%TYPE,
P_ID_TIPO IN USUARIO.ID_TIPO%TYPE,
P_RESULT OUT VARCHAR2
)
AS
BEGIN
    INSERT INTO USUARIO(NOMBRE,APELLIDO,CONTRASENA,CORREO,ID_TIPO)VALUES(P_NOMBRE,P_APELLIDO,P_CONTRASENA,P_CORREO,P_ID_TIPO);
    P_RESULT:= 'SE EJECUTO CORRECTAMENTE';
    COMMIT;
    EXCEPTION
        WHEN OTHERS THEN
        P_RESULT:='ERROR AL INSERTAR';
        ROLLBACK;
END;    


CREATE OR REPLACE PROCEDURE SP_ACTUALIZAR_USUARIO(
P_ID_USUARIO IN USUARIO.ID_USUARIO%TYPE,
P_NOMBRE IN USUARIO.NOMBRE%TYPE,
P_APELLIDO IN USUARIO.APELLIDO%TYPE,
P_CONTRASENA IN USUARIO.CONTRASENA%TYPE,
P_CORREO IN USUARIO.CORREO%TYPE,
P_ID_TIPO IN USUARIO.ID_TIPO%TYPE,
P_RESULT OUT VARCHAR2
)
AS
BEGIN
    UPDATE USUARIO
    SET NOMBRE = P_NOMBRE,APELLIDO = P_APELLIDO,CONTRASENA = P_CONTRASENA,CORREO=P_CORREO,ID_TIPO=P_ID_TIPO
    WHERE ID_USUARIO = P_ID_USUARIO;
    P_RESULT:= 'SE EJECUTO CORRECTAMENTE';
    COMMIT;
    EXCEPTION
        WHEN OTHERS THEN
        P_RESULT:='ERROR AL ACTUALIZAR';
        ROLLBACK;
END;    


CREATE OR REPLACE PROCEDURE SP_DELETE_USUARIO(
P_ID_USUARIO IN USUARIO.ID_USUARIO%TYPE,
P_RESULT OUT VARCHAR2
)
AS
BEGIN
    DELETE FROM USUARIO
    WHERE ID_USUARIO = P_ID_USUARIO;
    P_RESULT:='SE EJECUTO CORRECTAMENTE';
    COMMIT;
    EXCEPTION
        WHEN OTHERS THEN
            P_RESULT:='ERROR AL ELIMINAR';
        ROLLBACK;
END;

CREATE OR REPLACE PROCEDURE SP_SELECT_USUARIO(
P_CURSOR OUT SYS_REFCURSOR
)
AS
BEGIN
    OPEN P_CURSOR FOR
    SELECT ID_USUARIO,NOMBRE,APELLIDO,CONTRASENA,CORREO,ID_TIPO
    FROM USUARIO;
END;

--SECUENCIAS
CREATE SEQUENCE USUARIO_SEQ START WITH 5;

--TRIGGER
CREATE OR REPLACE TRIGGER USUARIO_TRIGGER
    BEFORE INSERT ON USUARIO
        FOR EACH ROW
    BEGIN
        SELECT USUARIO_SEQ.NEXTVAL
        INTO :NEW.ID_USUARIO
        FROM DUAL;
END;


    

